-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (
    SELECT a.ANIMAL_ID, a.NAME, datediff(b.DATETIME, a.DATETIME)
    FROM ANIMAL_INS a
        INNER JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
    ORDER BY 3 DESC
    LIMIT 2
) c
