-- 코드를 입력하세요
SELECT a.CAR_ID, a.CAR_TYPE, FEE
FROM CAR_RENTAL_COMPANY_CAR a 
    INNER JOIN (
        SELECT CAR_ID, ROUND((aa.DAILY_FEE * 30 / 100) * (100 - bb.DISCOUNT_RATE), 0) AS FEE
        FROM CAR_RENTAL_COMPANY_CAR aa
            LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN bb ON aa.CAR_TYPE = bb.CAR_TYPE
        WHERE bb.DURATION_TYPE = '30일 이상'
    ) c ON a.CAR_ID = c.CAR_ID
WHERE a.CAR_TYPE IN ('세단', 'SUV') AND FEE >= 500000 AND FEE < 2000000 
AND a.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' 
    )
ORDER BY FEE DESC, CAR_TYPE, CAR_ID