-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
, count(distinct USER_ID) AS PUCHASED_USERS
, round(count(distinct USER_ID) / (
    SELECT count(*)
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
)
GROUP BY YEAR, MONTH