-- 코드를 작성해주세요
WITH RECURSIVE t AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT c.ID, c.PARENT_ID, t.GENERATION + 1
    FROM ECOLI_DATA c
    JOIN t ON c.PARENT_ID = t.ID
)

SELECT COUNT(*) as 'COUNT', GENERATION
FROM t
LEFT JOIN ECOLI_DATA c ON t.ID = c.PARENT_ID
WHERE c.ID is null
GROUP BY GENERATION
ORDER BY GENERATION