-- 코드를 입력하세요
SELECT fh.FLAVOR
FROM FIRST_HALF fh
INNER JOIN (SELECT FLAVOR, sum(TOTAL_ORDER) TOTAL_ORDER FROM JULY GROUP BY FLAVOR) j ON fh.FLAVOR = j.FLAVOR
GROUP BY fh.FLAVOR
ORDER BY fh.TOTAL_ORDER + j.TOTAL_ORDER DESC
LIMIT 3;



# SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
# FROM FIRST_HALF

# SELECT SHIPMENT_ID, FLAVOR, TOTAL_ORDER
# FROM JULY