-- 코드를 입력하세요
SELECT MEMBER_NAME, REVIEW_TEXT, date_format(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW a
    JOIN MEMBER_PROFILE b ON a.MEMBER_ID = b.MEMBER_ID
WHERE a.MEMBER_ID = (
    SELECT a.MEMBER_ID
    FROM REST_REVIEW a
        JOIN MEMBER_PROFILE b ON a.MEMBER_ID = b.MEMBER_ID
    GROUP BY a.MEMBER_ID
    ORDER BY count(*) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT