-- 코드를 입력하세요
SELECT CATEGORY, sum(SALES) TOTAL_SALES
FROM BOOK a
    INNER JOIN BOOK_SALES b ON a.BOOK_ID = b.BOOK_ID
WHERE year(SALES_DATE) = 2022 AND month(SALES_DATE) = 1
GROUP BY a.CATEGORY
ORDER BY a.CATEGORY